from .player_ffplay import FFplayPlayer
from .player_mpv import MpvPlayer
from .player_vlc import VlcPlayer
from .player_mpg123 import Mpg123Player
from .player_cmus import CmusPlayer
from .player_simpleaudio import SimpleaudioPlayer
from .player_pyaudio import PyAudioPlayer
from .player_playsound import PlaysoundPlayer
from .p_auto import AutoPlayer
